# Docker Compose para APIs Refatoradas
# Sistema RAG - Configuração Otimizada para APIs v2.0.0

version: '3.8'

services:
  # API RAG Simples Refatorada
  api-simple:
    build:
      context: .
      dockerfile: Dockerfile.api-simple
    container_name: rag-api-simple
    ports:
      - "8001:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - API_LOG_LEVEL=info
      - API_WORKERS=2
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.3'
          memory: 512M
    networks:
      - rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # API Multi-Agente Refatorada
  api-multiagent:
    build:
      context: .
      dockerfile: Dockerfile.api-multiagent
    container_name: rag-api-multiagent
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_LOG_LEVEL=info
      - API_WORKERS=4
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
    profiles:
      - cache

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_rag.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx:rw
    depends_on:
      - api-simple
      - api-multiagent
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
    profiles:
      - loadbalancer

  # Prometheus para métricas (opcional)
  prometheus:
    image: prom/prometheus:latest
    container_name: rag-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - rag-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    profiles:
      - monitoring

  # Grafana para visualização (opcional)
  grafana:
    image: grafana/grafana:latest
    container_name: rag-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - rag-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  rag-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Perfis para diferentes cenários de deployment:
# docker-compose up                          # Apenas APIs
# docker-compose --profile cache up          # APIs + Redis  
# docker-compose --profile loadbalancer up   # APIs + Nginx
# docker-compose --profile monitoring up     # APIs + Prometheus + Grafana
# docker-compose --profile cache --profile monitoring up  # Tudo